spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
